### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by Suburbanno** [DeadMerc/Plug.dj#1]

**Comment by deadmerc** [comment]
Hi, i have one build, but it works so slowly, maybe in future i publish it in GooglePlay

**Comment by Suburbanno** [comment]
oh, ok

**Comment by Suburbanno** [comment]
@DeadMerc Any screenshot?

**Comment by deadmerc** [comment]
@Suburbanno in one-two days can give you link to app in play market

**Comment by Suburbanno** [comment]
ok

**Comment by Suburbanno** [comment]
5 days TT.TT

**Comment by deadmerc** [comment]
@Suburbanno App rejected, copyright.

**Comment by Suburbanno** [comment]
@DeadMerc Share the apk right here on github 
pls :(

**Comment by deadmerc** [comment]
@Suburbanno This, sry for late response, i prepare what app so slowly :D
https://dl.dropboxusercontent.com/u/105655494/plug.dj/app-release.apk

**Comment by Suburbanno** [comment]
@DeadMerc hey guy, nothing works, not even the login or guest

**Comment by deadmerc** [comment]
@Suburbanno Push guest, choose room, and wait

**Comment by Suburbanno** [comment]
@DeadMerc  I waited for 15 minutes and nothing happened, the same message is infinitely "Plugging you in...."

**Comment by deadmerc** [comment]
@Suburbanno dont know what happen on you phone.

**Comment by Suburbanno** [comment]
galaxy j2 duos 
5.1.1
fix?

**Comment by Suburbanno** [comment]
die?
